version: '3.7'

services:
  php-fpm:
    build: docker
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: nginx
    working_dir: /app
    ports:
      - 7777:80
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    container_name: postgresql
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: posts
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.7.5-management
    working_dir: /app
    hostname: rabbit-mq
    container_name: 'rabbit-mq'
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password    

 postgres_test:
    image: postgres:11
    ports:
      - 25432:5432
    container_name: 'postgresql_test'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'posts_test'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - dump:/app/dump
      - postgresql_test:/var/lib/postgresql/data

volumes:
  dump:
  postgresql:
  sentry-pgdb:
  postgresql_test: